### ISSUE TITLE
RRTStarReedsShepp creates a None type new node and generates error.

### ISSUE THREAD

**Issue by shivanshrathi** [AtsushiSakai/PythonRobotics#249]
I wanted to use RRTStar Reeds Shepp code for a set of pre-decided obstacle course of more than 2000 obstacles. I am getting an error due to creation of None Type object for  new_node.

Traceback (most recent call last):
  File "rrt_star_reeds_shepp_1.py", line 389, in <module>
    main()
  File "rrt_star_reeds_shepp_1.py", line 339, in main
    path = rrt_star_reeds_shepp.planning(animation=show_animation)
  File "rrt_star_reeds_shepp_1.py", line 93, in planning
    if self.check_collision(new_node, self.obstacle_list):
  File "/home/PythonRobotics-master/PythonRobotics-master/PathPlanning/RRTStar/../RRT/rrt.py", line 176, in check_collision
    dx_list = [ox - x for x in node.path_x]
AttributeError: 'NoneType' object has no attribute 'path_x'

I looked into it and I am getting this error when Reed Shepp Path planner doesn't returns a path. How can I solve this issue?

**Comment by AtsushiSakai** [comment]
@shivanshrathi That means, Reed Shepp Path planner cannot generate a path. So, we need to implement an error handling there.
