### ISSUE TITLE
Bug Report : Hybrid A*

### ISSUE THREAD

**Issue by guilyx** [AtsushiSakai/PythonRobotics#325]
Hey @AtsushiSakai, stumbled upon this when I tried the HybridAStar script :

**Describe the bug**
```
$ python hybrid_a_star.py
Start Hybrid A* planning
Traceback (most recent call last):
  File "/home/erwin/.local/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hybrid_a_star.py", line 466, in <module>
    main()
  File "hybrid_a_star.py", line 447, in main
    start, goal, ox, oy, XY_GRID_RESOLUTION, YAW_GRID_RESOLUTION)
  File "hybrid_a_star.py", line 341, in hybrid_a_star_planning
    for neighbor in get_neighbors(current, config, ox, oy, obkdtree):
  File "hybrid_a_star.py", line 140, in get_neighbors
    for steer, d in calc_motion_inputs():
  File "hybrid_a_star.py", line 133, in calc_motion_inputs
    for steer in np.concatenate((np.linspace(-MAX_STEER, MAX_STEER, N_STEER),[0.0])):
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/erwin/.local/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
```

**Expected behavior**
Running Hybrid AStar for the car model...

**Screenshots**
cf current behavior for traceback

**Desktop:**
```shell
$ python --version
Python 3.7.5
```
```shell
$ pip show numpy
Name: numpy
Version: 1.18.4
```
```shell
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
```

**Fix:**
N_STEER should be an integer in np.linespace(x, y, N_STEER) and it's a float. Converting it to integer should fix it

**Comment by AtsushiSakai** [comment]
@guilyx Can you make a PR to fix this?
